---
title: "mirna_deseq2_analysis"
author: "Isra Aman Aziz"
date: "2026-03-16"
output: html_document
---

```{r}
# Define project directories

data <- "data/"
results <-"results/"
plots <- "plots/"

getwd()
list.files(data)
```


```{r include=FALSE, results='hide'}
#Install required packages

if(!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DESeq2")

install.packages(c(
  "pheatmap",
  "ggplot2",
  "EnhancedVolcano",
  "ggrepel",
  "RColorBrewer"
))

```

```{r include=FALSE}
# loading necessary libraries

library(DESeq2)
library(ggplot2)
library(pheatmap)
library(EnhancedVolcano)
library(RColorBrewer)
library(ggrepel)
```


```{r}
#Load count matrix and metadata
counts <- read.csv(("data/miRNA_countmatrix.csv"),
                    row.names = 1)

meta <- read.csv(("data/sample_info.csv"),
                 row.names = 1)

head(counts)
head(meta)

```


```{r}
#aligning order of metadata according to countmatrix

meta <- meta[colnames(counts), ]


# sanity check

all(rownames(meta) == colnames(counts))

# Number of miRNAs
nrow(counts)

#number of samples
ncol(counts)
```

```{r}
# creating  Deseq2 Dataset

dds <- DESeqDataSetFromMatrix(
  countData = counts,
  colData = meta,
  design = ~dataset + condition
)

dds

```

```{r}
#filtering low quality counts mirna

keep <- rowSums(counts(dds) >= 10) >= 3

dds <- dds[keep, ]

dim(dds)

```

```{r}
#converting metadata to factors, and reference as healthy control

dds$condition <- factor(dds$condition)
dds$dataset <- factor(dds$dataset)


dds$condition <- relevel(dds$condition, ref = "Healthy Control")
```

```{r}
# Run DEA

dds <- DESeq(dds)
```

```{r}
# extract results with adp pvalue of 0.1

res <- results(dds, alpha = 0.1)

res_clean <- res[!is.na(res$padj), ]

summary(res)

```

```{r}
library(limma)

vsd <- varianceStabilizingTransformation(dds, blind = FALSE)


assay(vsd) <- removeBatchEffect(
  assay(vsd),
  batch = vsd$dataset
  )

pca_data <- plotPCA(
  vsd,
  intgroup = "condition",
  returnData = TRUE
  )

percentVar <- round(100 * attr(pca_data, "percentVar"))

pca_plot <- ggplot(pca_data, aes(x = PC1, y = PC2, color = condition)) +
  geom_point(size = 3) +
  
  labs( x = paste0("PC1: ", percentVar[1], "% variance"),
        y = paste0("PC2: ", percentVar[2], "% variance")
        ) +
  theme_classic()

ggsave("plots/pca_plot.png", plot = pca_plot, width = 8, height = 6, dpi = 500)
```

```{r}
# QC Check

p_hist <- ggplot(as.data.frame(res_clean), aes(x = pvalue)) +
  geom_histogram(bins = 50, fill = "steelblue", color = "white", na.rm = TRUE) +
  labs(title = "P-value distribution", x = "p-value", y = "frequency") +
  theme_classic()

ggsave("plots/distribution_plot.png", plot = p_hist, width = 7, height = 5, dpi = 500)
```

```{r}
# EXPORTING RAW P-VALUE CANDIDATES
sig_pval <- subset(res_clean, pvalue <= 0.05 &
                     abs(res_clean$log2FoldChange) >= 0.5)

sig_pval <- sig_pval[order(sig_pval$pvalue), ]

write.csv(as.data.frame(sig_pval),"results/p_value0.05_Significant_miRNAS.csv", row.names = TRUE)
```

```{r}
# Exporting padj values in csv
high_conf <- subset(res_clean, padj <= 0.1 &
                      abs(res_clean$log2FoldChange) >= 0.5)

high_conf <- high_conf[order(high_conf$padj), ]

nrow(high_conf)
head(high_conf)

write.csv(as.data.frame(high_conf),
          "results/padj0.1_Significant_miRNAS.csv", row.names = TRUE)

```

```{r}
# Prepare the full dataframe for plots
df <- as.data.frame(res_clean)

# Flag only the true biomarker candidates
df$Significant <- rownames(df) %in% rownames(high_conf)

# Create a label column: Only give a text label to the significant miRNAs
df$label <- ifelse(df$Significant, rownames(df), NA)
```

```{r}
# MA plot highlighting the exact candidates
ma_plot <- ggplot(df, aes(x = baseMean, y = log2FoldChange)) +
  geom_point(data = subset(df, !Significant), color = "grey70", size = 3.5, alpha = 1) +
  geom_point(data = subset(df, Significant), color = "firebrick", size = 3, alpha = 1) +
  geom_text_repel(aes(label = label), size = 3.5, max.overlaps = Inf, box.padding = 0.5) +
  
  scale_x_log10() +
  geom_hline(yintercept = 0, linetype = "solid", color = "black", linewidth = 0.5) +
  
  labs(
       x = "Mean Expression (log10 scale)",
       y = "Log2 Fold Change") +
  theme_classic()

ggsave("plots/MA_plot_labeled.png", plot = ma_plot, width = 9, height = 6, dpi = 500)
```

```{r}
# Volcano Plot highlighting the exact candidates
volcano <- ggplot(df, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(data = subset(df, !Significant), color = "grey70", size = 3.5, alpha = 1) +
  geom_point(data = subset(df, Significant), color = "firebrick", size = 3, alpha = 1) +
  geom_text_repel(aes(label = label), size = 3.5, max.overlaps = Inf, box.padding = 0.5) +
  
  geom_vline(xintercept = c(-lfc_threshold, lfc_threshold), linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = -log10(padj_threshold), linetype = "dashed", alpha = 0.5) +
  
  labs(
       x = "Log2 Fold Change",
       y = "-Log10(Adjusted P-value)") +
  theme_classic() 

ggsave("plots/volcano_plot_labeled.png", plot = volcano, width = 8, height = 7, dpi = 500)
```

```{r}
table(meta$dataset, meta$condition)
```
```{r}
# exporting ml_candidates

write.csv(
  data.frame(miRNA = rownames(high_conf)),
  "results/ml_candidate_miRNAs.csv",
  row.names = FALSE
)
```


