---
title: "Functional Enrichment Analysis of Schizophrenia Hub Genes"
author: "Isra Aman Aziz"
---

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(ggplot2)
library(DOSE)
library(dplyr)
```

```{r}
genes <- read.csv("results/hub_genes.csv")

head(genes)

gene_symbols <- unique(genes$Gene)

cat("Number of hub genes:", length(gene_symbols))
```

```{r}
gene_df <- bitr(
  gene_symbols,
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Hs.eg.db
)

head(gene_df)

gene_ids <- unique(gene_df$ENTREZID)

cat("Mapped genes:", length(gene_ids))
```

```{r}
go_enrich <- enrichGO(
  gene = gene_ids,
  OrgDb = org.Hs.eg.db,
  ont = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.05,
  readable = TRUE
)

go_df <- as.data.frame(go_enrich)

head(go_df)
```

```{r}
# Filter schizophrenia-relevant GO terms

keywords <- c(
  "neuro",
  "brain",
  "neuron",
  "synapse",
  "telencephalon",
  "limbic",
  "apoptosis",
  "stress",
  "neurogenesis",
  "axon",
  "glial",
  "dendrite",
  "signal",
  "nervous system",
  "cell death",
  "extracellular matrix",
  "Pallium development",
  "Synaptic transmission, GABAergic"
)

go_df_filtered <- go_df %>%
  filter(
    grepl(
      paste(keywords, collapse = "|"),
      Description,
      ignore.case = TRUE
    )
  ) %>%
  arrange(p.adjust)

go_df_filtered
```

```{r}
remove_terms_go <- c(
  "epithelial",
  "endothelial",
  "extracellular matrix assembly",
  "collagen",
  "amino acid"
)

go_filtered <- go_enrich

go_filtered@result <- go_filtered@result %>%
  filter(
    grepl(
      paste(keywords, collapse = "|"),
      Description,
      ignore.case = TRUE
    )
  ) %>%
  filter(
    !grepl(
      paste(remove_terms_go, collapse = "|"),
      Description,
      ignore.case = TRUE
    )
  ) %>%
  arrange(p.adjust)
```

```{r}
go_plot <- dotplot(
  go_filtered,
  showCategory = 10,
  font.size = 10,
) +
theme_bw(base_size = 15) +
theme(
  plot.title = element_text(hjust = 0.5, face = "bold"),
  axis.text.y = element_text(size = 7.5)
)
```

```{r}
go_sim <- pairwise_termsim(go_filtered)

emapplot(
  go_sim,
  showCategory = 15,

) +
ggtitle("GO-BP Enrichment Map") +
theme(
  plot.title = element_text(
    hjust = 0.5,
    face = "bold"
  )
)
```

```{r}
kegg_enrich <- enrichKEGG(
  gene = gene_ids,
  organism = "hsa",
  pvalueCutoff = 0.05
)

kegg_enrich <- setReadable(
  kegg_enrich,
  OrgDb = org.Hs.eg.db,
  keyType = "ENTREZID"
)

kegg_df <- as.data.frame(kegg_enrich)

head(kegg_df)
```

```{r}
remove_terms <- c(
  "cancer",
  "viral",
  "hepatitis",
  "papillomavirus",
  "diabetic",
  "longevity",
  "EGFR",
  "prolactin",
  "Amoebiasis",
  "leukemia"
)

kegg_filtered <- kegg_enrich

kegg_filtered@result <- kegg_filtered@result %>%
  filter(
    !grepl(
      paste(remove_terms, collapse = "|"),
      Description,
      ignore.case = TRUE
    )
  )
```

```{r}
kegg_plot <- dotplot(
  kegg_filtered,
  showCategory = 10,
  font.size = 10,
) +
theme_bw(base_size = 10) +
theme(
  plot.title = element_text(
    hjust = 0.5,
    face = "bold"
  ),
  axis.text.y = element_text(size = 10)
)
```

```{r}
ggsave(
  "plots/GO_BP_dotplot.png",
  plot = go_plot,
  width = 10,
  height = 7,
  dpi = 600
)

ggsave(
  "plots/KEGG_dotplot.png",
  plot = kegg_plot,
  width = 10,
  height = 7,
  dpi = 600
)
```

```{r}
write.csv(
  go_df,
  "results/GO_BP_results.csv",
  row.names = FALSE
)

write.csv(
  kegg_df,
  "results/KEGG_results.csv",
  row.names = FALSE
)
```

